// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXj6-3XLeakh5TX-4PGYxGERFnL92gnBc',
    appId: '1:831248601177:web:8a187cedb0679df4c82148',
    messagingSenderId: '831248601177',
    projectId: 'crackitx-96076',
    authDomain: 'crackitx-96076.firebaseapp.com',
    storageBucket: 'crackitx-96076.firebasestorage.app',
    measurementId: 'G-98K69CSR7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXMYiTmSWN8MPl_J8bEvW2rovtcAWVTU',
    appId: '1:831248601177:android:812952ebdc56dd85c82148',
    messagingSenderId: '831248601177',
    projectId: 'crackitx-96076',
    storageBucket: 'crackitx-96076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKL7l7dJ4d9xI3PFLx5OspccxRYDC9RGk',
    appId: '1:831248601177:ios:7a99216ba4593b82c82148',
    messagingSenderId: '831248601177',
    projectId: 'crackitx-96076',
    storageBucket: 'crackitx-96076.firebasestorage.app',
    iosBundleId: 'com.contentive.crackitx',
  );

}