// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDllM69lWgLTt5DdUQfLyvvrNK_XKonKXw',
    appId: '1:219919089326:web:92b0f16bf4a98832afb73f',
    messagingSenderId: '219919089326',
    projectId: 'crackitx',
    authDomain: 'crackitx.firebaseapp.com',
    storageBucket: 'crackitx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYDiDiS9ho3SXdOUKMMPv6PLu9iXFGSRw',
    appId: '1:219919089326:android:45feb2a52e1e9cd1afb73f',
    messagingSenderId: '219919089326',
    projectId: 'crackitx',
    storageBucket: 'crackitx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOtjKz9SCuM_BAd2GhaCEd0pcG_ln7C8',
    appId: '1:219919089326:ios:00f5119f7a55341bafb73f',
    messagingSenderId: '219919089326',
    projectId: 'crackitx',
    storageBucket: 'crackitx.firebasestorage.app',
    iosBundleId: 'com.contentive.crackitx',
  );

}