// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPDruIF3PUNUemrXWVX_H1TECAll8dJec',
    appId: '1:243295987001:web:2e6cce918237ee735174e8',
    messagingSenderId: '243295987001',
    projectId: 'offline-14ce6',
    authDomain: 'offline-14ce6.firebaseapp.com',
    storageBucket: 'offline-14ce6.firebasestorage.app',
    measurementId: 'G-RTYXPH7TRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVmQc9t5B1aGqbnLIGeEYZC3BAIqwxTeA',
    appId: '1:243295987001:android:71da0f5c83e72c785174e8',
    messagingSenderId: '243295987001',
    projectId: 'offline-14ce6',
    storageBucket: 'offline-14ce6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8iD0iUA6jhQDLrNwDLI8HgicuIY7sNZw',
    appId: '1:243295987001:ios:ff527a97083bc5935174e8',
    messagingSenderId: '243295987001',
    projectId: 'offline-14ce6',
    storageBucket: 'offline-14ce6.firebasestorage.app',
    iosBundleId: 'com.example.offlineTestApp',
  );

}